---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny # running shiny at background
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r import data}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
         latitude, longitude) %>%
  filter(!is.na(rating))
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r widgets}
boros = nyc_airbnb %>% distinct(boro) %>% pull()

# selectInput widget 1
selectInput("boro_choice", # the name for this part
            label = h3("Select boro"), # label for user
            choices = boros, selected = "Manhattan") # default selection

# sliderInput widget 2
max_price = 1000
min_price = nyc_airbnb %>% distinct(price) %>% min()
sliderInput("price_range", 
            label = h3("Choose price range"), 
            min = min_price, 
            max = max_price, value = c(100, 400))

# radioButtons widget
room_choice = nyc_airbnb %>% distinct(room_type) %>% pull()
radioButtons("room_choice", 
             label = h3("Choose room type"),
             choices = room_choice, 
             selected = "Entire home/apt")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r chart A}
renderPlotly({
  nyc_airbnb %>%
  filter(boro == input$boro_choice, 
         price %in% input$price_range[1]:input$price_range[2],
         room_type == input$room_choice) %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r chart B}
renderPlotly({
  nyc_airbnb %>% 
    filter(boro == input$boro_choice, 
           price %in% input$price_range[1]:input$price_range[2],
           room_type == input$room_choice) %>%
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
    plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
})
```

### Chart C

```{r chart C}
renderPlotly({ 
  common_neighborhoods =
    nyc_airbnb %>% 
    filter(boro == input$boro_choice,
           price %in% input$price_range[1]:input$price_range[2],
           room_type == input$room_choice) %>%
    count(neighbourhood, sort = TRUE) %>% 
    top_n(8) %>% 
    select(neighbourhood)

  nyc_airbnb %>%
    filter(boro == input$boro_choice,
                          price %in% input$price_range[1]:input$price_range[2],
                          room_type == input$room_choice) %>%
    inner_join(., common_neighborhoods, by = "neighbourhood") %>% 
    plot_ly(y = ~price, color = ~neighbourhood, type = "box")
})
```

